
alphafold3_databases: /scratch/ashiver/af3/db/
alphafold3_docker: /scratch/ashiver/af3/alphafold3.sif
nvidia_smi_cmd: nvidia-smi --query-gpu=index,count,timestamp,name,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used --format=csv,nounits --loop
